baseURL: http://something-fresh.org/
languageCode: en-us
title: True Pagamentos
theme: hugo-fresh
publishDir: .
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: 
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/true-pay-white.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: True Pagamentos
    # Hero subtitle (optional)
    subtitle: Já imaginou não ter mais que antecipar recebíveis de cartão e ainda conseguir mais crédito com seus fornecedores?
    # Button text
    buttontext: Entre em Contato
    # Where the main hero button links to
    buttonlink: "https://forms.gle/mmXU6kFBVfCoYK1W9"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
  section3:
    title: Uma plataforma
    subtitle: Para gerenciar seus recebíveis e pagar seus fornecedores
    image: illustrations/mockups/app-platform.png
    buttonText: Entre em Contato
    buttonLink: "https://forms.gle/mmXU6kFBVfCoYK1W9"
